### ISSUE TITLE
Something wrong in extracting weights?

### ISSUE THREAD

**Issue by tjiagoM** [greenelab/tybalt#144]
In `extract_tybalt_weights.ipynb` notebook, you defined a function `output_high_weight_genes`.

At a certain point you have these 2 lines:
`hw_pos_df = pd.DataFrame(encoding_df[encoding_df > encoding_df.std() * thresh])`
`hw_neg_df = pd.DataFrame(encoding_df[encoding_df < -encoding_df.std() * thresh])`

It seems like you are trying to get the most extreme values away from the mean, but you don't really have the mean here. Shouldn't it be something like this?
`hw_pos_df = pd.DataFrame(encoding_df[encoding_df > encoding_df.mean() + encoding_df.std() * thresh])`
`hw_neg_df = pd.DataFrame(encoding_df[encoding_df < encoding_df.mean() - encoding_df.std() * thresh])`

**Comment by gwaygenomics** [comment]
ah, thanks for pointing this out @tjiagoM - I will take a look

**Comment by gwaygenomics** [comment]
Going to address today! Finally getting to this
