### ISSUE TITLE
Matching pancancer expression to metadata

### ISSUE THREAD

**Issue by GlastonburyC** [greenelab/tybalt#152]
Hi @gwaygenomics @cgreene 
I would like to map samples (index values) in `pancan_scaled_rnaseq.tsv.gz` to the metadata `tcga-clinical_data.tsv`.

Currently the index values for the rnaseq are not unique and I am unable to match them to the metadata.

Could you please advise on how, for example, I could subset the pancancer data to just a single cancer subtype (tying it to the metadata).

**Comment by gwaybio** [comment]
`pancan_scaled_rnaseq.tsv.gz` includes sample level information while `tcga-clinical_data.tsv` includes patient level information. The sample level information identifiers are much more descriptive than the patient level information.

Mapping between the two files can be done by subsetting TCGA barcodes. Info here: https://docs.gdc.cancer.gov/Encyclopedia/pages/TCGA_Barcode/ 

This file might also be helpful: https://github.com/greenelab/pancancer/blob/master/data/sample_freeze.tsv

**Comment by GlastonburyC** [comment]
Isn't it the opposite?
`pancan_scaled_rnaseq.tsv.gz` looks like this:

![Screenshot 2019-11-12 at 16 57 02](https://user-images.githubusercontent.com/4210507/68693093-91dde000-056e-11ea-8d54-da47128cc343.png)

Where as the clinical data contains the full barcode.
![Screenshot 2019-11-12 at 17 06 04](https://user-images.githubusercontent.com/4210507/68693180-bc2f9d80-056e-11ea-9b75-0ee5ba1bdb71.png)

**Comment by gwaybio** [comment]
in either direction, the mapping can be done the same way. I don't think i've used the `portion_id` column though. Is there a `sample_id` column or something similar?

**Comment by GlastonburyC** [comment]
This file: https://github.com/greenelab/pancancer/blob/master/data/sample_freeze.tsv
made it trivial. Thanks
